-- Cell-room booking system schema
-- Run in the Supabase SQL Editor after creating a project.

create extension if not exists pgcrypto;
create extension if not exists btree_gist;

do $$ begin
  create type public.user_role as enum ('admin', 'member');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.user_status as enum ('pending', 'approved', 'suspended');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.booking_status as enum ('booked', 'in_use', 'completed', 'cancelled', 'no_show');
exception when duplicate_object then null; end $$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null default '',
  display_name text not null default '',
  phone text not null default '',
  role public.user_role not null default 'member',
  status public.user_status not null default 'pending',
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.equipment (
  id bigint generated by default as identity primary key,
  name text not null unique,
  type text not null default '其他',
  location text not null default '',
  sort_order integer not null default 100,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.reservations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  equipment_id bigint not null references public.equipment(id) on delete restrict,
  start_at timestamptz not null,
  end_at timestamptz not null,
  purpose text not null default '',
  status public.booking_status not null default 'booked',
  booked_by_name text not null default '',
  booked_by_email text not null default '',
  cancelled_at timestamptz,
  cancelled_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint reservations_time_order check (end_at > start_at),
  constraint reservations_same_local_day check (
    (start_at at time zone 'Asia/Shanghai')::date =
    (((end_at - interval '1 microsecond') at time zone 'Asia/Shanghai')::date)
  )
);

create table if not exists public.usage_sessions (
  id uuid primary key default gen_random_uuid(),
  reservation_id uuid not null unique references public.reservations(id) on delete cascade,
  actual_start timestamptz not null default now(),
  actual_end timestamptz,
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint usage_time_order check (actual_end is null or actual_end >= actual_start)
);

alter table public.reservations drop constraint if exists reservations_no_overlap;
alter table public.reservations
  add constraint reservations_no_overlap
  exclude using gist (
    equipment_id with =,
    tstzrange(start_at, end_at, '[)') with &&
  )
  where (status in ('booked', 'in_use'));

create index if not exists reservations_start_at_idx on public.reservations(start_at);
create index if not exists reservations_user_id_idx on public.reservations(user_id);
create index if not exists reservations_equipment_id_idx on public.reservations(equipment_id);
create index if not exists profiles_status_idx on public.profiles(status);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_touch_updated_at on public.profiles;
create trigger profiles_touch_updated_at before update on public.profiles
for each row execute function public.touch_updated_at();

drop trigger if exists equipment_touch_updated_at on public.equipment;
create trigger equipment_touch_updated_at before update on public.equipment
for each row execute function public.touch_updated_at();

drop trigger if exists reservations_touch_updated_at on public.reservations;
create trigger reservations_touch_updated_at before update on public.reservations
for each row execute function public.touch_updated_at();

drop trigger if exists usage_sessions_touch_updated_at on public.usage_sessions;
create trigger usage_sessions_touch_updated_at before update on public.usage_sessions
for each row execute function public.touch_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  insert into public.profiles (id, email, display_name, phone, student_staff_id, advisor)
  values (
    new.id,
    coalesce(new.email, ''),
    coalesce(new.raw_user_meta_data ->> 'display_name', ''),
    coalesce(new.raw_user_meta_data ->> 'phone', ''),
    coalesce(new.raw_user_meta_data ->> 'student_staff_id', ''),
    coalesce(new.raw_user_meta_data ->> 'advisor', '')
  )
  on conflict (id) do update set
    email = excluded.email,
    display_name = case when public.profiles.display_name = '' then excluded.display_name else public.profiles.display_name end,
    phone = case when public.profiles.phone = '' then excluded.phone else public.profiles.phone end,
    student_staff_id = case when public.profiles.student_staff_id = '' then excluded.student_staff_id else public.profiles.student_staff_id end,
    advisor = case when public.profiles.advisor = '' then excluded.advisor else public.profiles.advisor end;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

insert into public.profiles (id, email, display_name, phone, student_staff_id, advisor)
select
  u.id,
  coalesce(u.email, ''),
  coalesce(u.raw_user_meta_data ->> 'display_name', ''),
  coalesce(u.raw_user_meta_data ->> 'phone', ''),
  coalesce(u.raw_user_meta_data ->> 'student_staff_id', ''),
  coalesce(u.raw_user_meta_data ->> 'advisor', '')
from auth.users u
on conflict (id) do nothing;

create or replace function public.current_profile_role()
returns public.user_role
language sql
stable
security definer
set search_path = public, auth
as $$
  select role from public.profiles where id = auth.uid()
$$;

create or replace function public.current_profile_status()
returns public.user_status
language sql
stable
security definer
set search_path = public, auth
as $$
  select status from public.profiles where id = auth.uid()
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public, auth
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin' and status = 'approved'
  )
$$;

create or replace function public.is_approved()
returns boolean
language sql
stable
security definer
set search_path = public, auth
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and status = 'approved'
  )
$$;

create or replace function public.promote_initial_admin()
returns boolean
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_user_id uuid := auth.uid();
  v_email text;
  v_admin_exists boolean;
begin
  if v_user_id is null then
    return false;
  end if;

  select email into v_email from public.profiles where id = v_user_id;
  select exists (select 1 from public.profiles where role = 'admin' and status = 'approved') into v_admin_exists;

  if v_admin_exists or v_email is null or v_email = '' then
    return false;
  end if;

  update public.profiles
  set role = 'admin', status = 'approved', approved_at = now()
  where id = v_user_id and email = v_email;

  return found;
end;
$$;

create or replace function public.update_my_profile(
  p_display_name text,
  p_phone text,
  p_student_staff_id text,
  p_advisor text
)
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if auth.uid() is null then
    raise exception 'not authenticated';
  end if;
  update public.profiles
  set display_name = coalesce(p_display_name, ''),
      phone = coalesce(p_phone, ''),
      student_staff_id = coalesce(p_student_staff_id, ''),
      advisor = coalesce(p_advisor, '')
  where id = auth.uid();
end;
$$;

create or replace function public.create_booking(
  p_equipment_id bigint,
  p_start_at timestamptz,
  p_end_at timestamptz,
  p_purpose text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_user_id uuid := auth.uid();
  v_profile public.profiles%rowtype;
  v_booking_id uuid;
  v_local_day date;
  v_has_conflict boolean;
begin
  if v_user_id is null then
    raise exception 'not authenticated';
  end if;

  select * into v_profile from public.profiles where id = v_user_id;
  if v_profile.id is null or v_profile.status <> 'approved' then
    raise exception 'not approved';
  end if;

  if p_end_at <= p_start_at then
    raise exception '结束时间必须晚于开始时间';
  end if;

  if (p_start_at at time zone 'Asia/Shanghai')::date <>
     (((p_end_at - interval '1 microsecond') at time zone 'Asia/Shanghai')::date) then
    raise exception '预约必须位于同一天内';
  end if;

  if (p_end_at - p_start_at) > interval '24 hours' then
    raise exception '单次预约不能超过 24 小时';
  end if;

  if not exists (select 1 from public.equipment where id = p_equipment_id and active = true) then
    raise exception '设备不存在或已停用';
  end if;

  v_local_day := (p_start_at at time zone 'Asia/Shanghai')::date;
  perform pg_advisory_xact_lock(hashtext(p_equipment_id::text || ':' || v_local_day::text));

  select exists (
    select 1
    from public.reservations r
    where r.equipment_id = p_equipment_id
      and r.status in ('booked', 'in_use')
      and tstzrange(r.start_at, r.end_at, '[)') && tstzrange(p_start_at, p_end_at, '[)')
  ) into v_has_conflict;

  if v_has_conflict then
    raise exception '该设备在所选时间段已有预约';
  end if;

  insert into public.reservations (
    user_id, equipment_id, start_at, end_at, purpose, status, booked_by_name, booked_by_email
  ) values (
    v_user_id, p_equipment_id, p_start_at, p_end_at, coalesce(p_purpose, ''), 'booked',
    coalesce(v_profile.display_name, v_profile.email, ''), coalesce(v_profile.email, '')
  ) returning id into v_booking_id;

  return jsonb_build_object('id', v_booking_id);
end;
$$;

create or replace function public.cancel_booking(p_booking_id uuid)
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_user_id uuid := auth.uid();
  v_booking public.reservations%rowtype;
begin
  select * into v_booking from public.reservations where id = p_booking_id for update;
  if v_booking.id is null then
    raise exception '预约不存在';
  end if;
  if v_booking.user_id <> v_user_id and not public.is_admin() then
    raise exception 'not authorized';
  end if;
  if v_booking.status not in ('booked', 'in_use') then
    raise exception '当前状态不能取消';
  end if;
  update public.reservations
  set status = 'cancelled', cancelled_at = now(), cancelled_by = v_user_id
  where id = p_booking_id;
end;
$$;

create or replace function public.start_usage(p_booking_id uuid)
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_booking public.reservations%rowtype;
  v_user_id uuid := auth.uid();
begin
  select * into v_booking from public.reservations where id = p_booking_id for update;
  if v_booking.id is null then
    raise exception '预约不存在';
  end if;
  if v_booking.user_id <> v_user_id and not public.is_admin() then
    raise exception 'not authorized';
  end if;
  if v_booking.status <> 'booked' then
    raise exception '只有已预约状态可以开始使用';
  end if;
  if now() < v_booking.start_at - interval '15 minutes' then
    raise exception '尚未到预约开始时间，最早可提前 15 分钟开始';
  end if;
  update public.reservations set status = 'in_use' where id = p_booking_id;
  insert into public.usage_sessions (reservation_id, actual_start)
  values (p_booking_id, now())
  on conflict (reservation_id) do update set actual_start = excluded.actual_start, actual_end = null;
end;
$$;

create or replace function public.complete_usage(p_booking_id uuid, p_notes text default '')
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_booking public.reservations%rowtype;
  v_user_id uuid := auth.uid();
begin
  select * into v_booking from public.reservations where id = p_booking_id for update;
  if v_booking.id is null then
    raise exception '预约不存在';
  end if;
  if v_booking.user_id <> v_user_id and not public.is_admin() then
    raise exception 'not authorized';
  end if;
  if v_booking.status not in ('booked', 'in_use') then
    raise exception '当前状态不能结束使用';
  end if;
  insert into public.usage_sessions (reservation_id, actual_start, actual_end, notes)
  values (p_booking_id, now(), now(), coalesce(p_notes, ''))
  on conflict (reservation_id) do update
    set actual_end = now(), notes = coalesce(p_notes, '');
  update public.reservations set status = 'completed' where id = p_booking_id;
end;
$$;

create or replace function public.mark_no_show(p_booking_id uuid)
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if not public.is_admin() then
    raise exception 'not authorized';
  end if;
  update public.reservations
  set status = 'no_show'
  where id = p_booking_id and status in ('booked', 'in_use');
  if not found then
    raise exception '当前状态不能标记未到';
  end if;
end;
$$;

create or replace view public.reservation_usage_summary
with (security_invoker = true)
as
select
  r.id,
  r.user_id,
  r.equipment_id,
  e.name as equipment_name,
  p.display_name as user_name,
  p.email as user_email,
  r.start_at,
  r.end_at,
  r.purpose,
  r.status,
  r.booked_by_name,
  r.created_at,
  floor(extract(epoch from (r.end_at - r.start_at)) / 60)::integer as reserved_minutes,
  case
    when us.actual_end is not null then floor(extract(epoch from (us.actual_end - us.actual_start)) / 60)::integer
    else null
  end as actual_minutes,
  us.actual_start,
  us.actual_end,
  us.notes
from public.reservations r
join public.equipment e on e.id = r.equipment_id
join public.profiles p on p.id = r.user_id
left join public.usage_sessions us on us.reservation_id = r.id;

insert into public.equipment (name, type, location, sort_order, active)
values
  ('超净工作台 1', '超净工作台', '细胞间操作区', 10, true),
  ('超净工作台 2', '超净工作台', '细胞间操作区', 20, true),
  ('培养箱 1', '培养箱', '细胞间培养区', 30, true),
  ('培养箱 2', '培养箱', '细胞间培养区', 40, true),
  ('培养箱 3', '培养箱', '细胞间培养区', 50, true),
  ('培养箱 4', '培养箱', '细胞间培养区', 60, true)
on conflict (name) do update set
  type = excluded.type,
  location = excluded.location,
  sort_order = excluded.sort_order;

alter table public.profiles enable row level security;
alter table public.equipment enable row level security;
alter table public.reservations enable row level security;
alter table public.usage_sessions enable row level security;

drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles
for select to authenticated
using (id = auth.uid() or public.is_admin());

drop policy if exists profiles_admin_update on public.profiles;
create policy profiles_admin_update on public.profiles
for update to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists equipment_select on public.equipment;
create policy equipment_select on public.equipment
for select to authenticated
using (public.is_approved() or public.is_admin());

drop policy if exists equipment_admin_write on public.equipment;
create policy equipment_admin_write on public.equipment
for all to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists reservations_select on public.reservations;
create policy reservations_select on public.reservations
for select to authenticated
using (public.is_approved() or public.is_admin());

drop policy if exists usage_sessions_select on public.usage_sessions;
create policy usage_sessions_select on public.usage_sessions
for select to authenticated
using (
  public.is_admin()
  or exists (
    select 1 from public.reservations r
    where r.id = usage_sessions.reservation_id and r.user_id = auth.uid()
  )
);

grant usage on schema public to authenticated;
grant select on public.equipment to authenticated;
grant select on public.reservations to authenticated;
grant select on public.profiles to authenticated;
grant select on public.usage_sessions to authenticated;
grant select on public.reservation_usage_summary to authenticated;
grant insert, update on public.equipment to authenticated;
grant update on public.profiles to authenticated;
grant usage, select on all sequences in schema public to authenticated;

grant execute on function public.promote_initial_admin() to authenticated;
grant execute on function public.update_my_profile(text, text, text, text) to authenticated;
grant execute on function public.create_booking(bigint, timestamptz, timestamptz, text) to authenticated;
grant execute on function public.cancel_booking(uuid) to authenticated;
grant execute on function public.start_usage(uuid) to authenticated;
grant execute on function public.complete_usage(uuid, text) to authenticated;
grant execute on function public.mark_no_show(uuid) to authenticated;

alter default privileges in schema public grant select on tables to authenticated;



-- Reservation editing and admin deletion.

create or replace function public.update_booking(
  p_booking_id uuid,
  p_equipment_id bigint,
  p_start_at timestamptz,
  p_end_at timestamptz,
  p_purpose text default ''
)
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_user_id uuid := auth.uid();
  v_booking public.reservations%rowtype;
  v_local_day date;
  v_has_conflict boolean;
begin
  if v_user_id is null then
    raise exception 'not authenticated';
  end if;

  if not public.is_admin() and not public.is_approved() then
    raise exception 'not approved';
  end if;

  select * into v_booking from public.reservations where id = p_booking_id for update;
  if v_booking.id is null then
    raise exception '预约不存在';
  end if;

  if v_booking.user_id <> v_user_id and not public.is_admin() then
    raise exception 'not authorized';
  end if;

  if v_booking.status <> 'booked' then
    raise exception '只有“已预约”状态可以修改';
  end if;

  if not public.is_admin() and now() >= v_booking.start_at then
    raise exception '预约开始后不能自行修改';
  end if;

  if not public.is_admin() and now() >= p_start_at then
    raise exception '新的预约时间必须晚于当前时间';
  end if;

  if p_end_at <= p_start_at then
    raise exception '结束时间必须晚于开始时间';
  end if;

  if (p_start_at at time zone 'Asia/Shanghai')::date <>
     (((p_end_at - interval '1 microsecond') at time zone 'Asia/Shanghai')::date) then
    raise exception '预约必须位于同一天内';
  end if;

  if (p_end_at - p_start_at) > interval '24 hours' then
    raise exception '单次预约不能超过 24 小时';
  end if;

  if not exists (select 1 from public.equipment where id = p_equipment_id and active = true) then
    raise exception '设备不存在或已停用';
  end if;

  v_local_day := (p_start_at at time zone 'Asia/Shanghai')::date;
  perform pg_advisory_xact_lock(hashtext(p_equipment_id::text || ':' || v_local_day::text));

  select exists (
    select 1
    from public.reservations r
    where r.id <> p_booking_id
      and r.equipment_id = p_equipment_id
      and r.status in ('booked', 'in_use')
      and tstzrange(r.start_at, r.end_at, '[)') && tstzrange(p_start_at, p_end_at, '[)')
  ) into v_has_conflict;

  if v_has_conflict then
    raise exception '该设备在所选时间段已有预约';
  end if;

  update public.reservations
  set equipment_id = p_equipment_id,
      start_at = p_start_at,
      end_at = p_end_at,
      purpose = coalesce(p_purpose, '')
  where id = p_booking_id;
end;
$$;

create or replace function public.delete_booking(p_booking_id uuid)
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if not public.is_admin() then
    raise exception 'not authorized';
  end if;

  delete from public.reservations where id = p_booking_id;
  if not found then
    raise exception '预约不存在';
  end if;
end;
$$;

grant execute on function public.update_booking(uuid, bigint, timestamptz, timestamptz, text) to authenticated;
grant execute on function public.delete_booking(uuid) to authenticated;
